version: "3"

services:

  nifi:
    container_name: nifi
    image: apache/nifi:latest
    restart: unless-stopped
    volumes:
      - /nifi:/nifi
    ports:
      - "8080:8080"
    environment:
      - NIFI_WEB_HTTP_PORT=8080

  nifi-registry:
    container_name: nifi-registry
    image: apache/nifi-registry:latest
    restart: unless-stopped
    ports:
      - "18080:18080" 
